---
title: "Libre para elegir"
baseURL: "https://libreparaelegir.netlify.app"
theme: "hugo-theme-zen"
languageCode: "en-GB"
defaultContentLanguage: "en"
pluralizelisttitles: false
removePathAccents: true
paginate: 10
paginatePath: "page"
rssLimit: 20
author:
  name: "Jose Luis Manzanares"
  url: "https://libreparaelegir.netlify.app/"
  avatar: "path/to/some-image.jpg"

outputFormats:
  SearchIndex:
    mediaType: "application/json"
    baseName: "searchindex"
    isPlainText: true
    notAlternative: true

outputs:
  home: ["HTML","RSS", "JSON", "SearchIndex"]
  section: ["HTML","RSS", "JSON"]

params:
  cookieConsent: false
  contact: "jlmanzanaresrivera@gmail.com"
  copyright: "<!--Creative Commons License-->This site is licensed under a [Creative Commons Attribution-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-sa/4.0/).<!--/Creative Commons License-->"
  description: "The zen theme for Hugo example site."
  dateformat: "2 January, 2006"
  favicon: "apple-touch-icon.png"
  feedlinks: true
  footer: "Created with passion by [insightAnalytics](https://insight4health.netlify.app/) and the [Zen theme](https://github.com/frjo/hugo-theme-zen)."
  icon: "apple-touch-icon.png"
  image: "apple-touch-icon.png"
  imageMaxWidth: 400
  mobileMenu: true
  poweredby: false
  sidebar: true
  submitted: true
